{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}-apiserver
  labels: {{- include "frontend.labels.standard" . | nindent 4 }}
{{- end -}}
