apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}-apiserver
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.apiserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: api
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
