apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels: {{- include "frontend.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {{- include "frontend.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "frontend.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "common.names.fullname" . }}-frontend
      securityContext: {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-frontend
        securityContext: {{- toYaml .Values.frontend.securityContext | nindent 12 }}
        {{- with .Values.frontend.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        image: {{ include "frontend.image" . }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        {{- with .Values.frontend.env }}
        env: {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        #- name: config
        #  mountPath: /app/static
        {{- if .Values.frontend.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            port: {{ .Values.frontend.livenessProbe.port | default 8080 }}
            path: {{ .Values.frontend.livenessProbe.path | default "/" }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds | default 45 }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds | default 2 }}
          successThreshold: {{ .Values.frontend.livenessProbe.successThreshold | default 1 }}
          failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- if .Values.apiserver.livenessProbe.enabled }}
        readinessProbe:
          httpGet:
            port: {{ .Values.frontend.readinessProbe.port | default 8080 }}
            path: {{ .Values.frontend.readinessProbe.path | default "/" }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds | default 45 }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds | default 5 }}
          successThreshold: {{ .Values.frontend.readinessProbe.successThreshold | default 1 }}
          failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold | default 3 }}
        {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      # https://github.com/DependencyTrack/frontend/issues/60
      # - name: config
      #  configMap:
      #    name: {{ include "common.names.fullname" . }}-frontend
      #    items:
      #    - key: config.json
      #      path: config.json
