apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "common.names.fullname" . }}-frontend
      securityContext: {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-frontend
        securityContext: {{- toYaml .Values.frontend.securityContext | nindent 12 }}
        {{- with .Values.frontend.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        {{- with .Values.frontend.env }}
        env: {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
