{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dependency-track-frontend.serviceAccountName" . }}
  labels:
{{ include "dependency-track.labels" . | indent 4 }}
{{- end -}}
