apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}-frontend
  labels:
{{ include "dependency-track-frontend.labels" . | indent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "dependency-track.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}-frontend
